# Generated by Django 5.1.4 on 2024-12-14 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_showroom_alter_carlist_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='ShowRoomlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='car_app.showroom'),
        ),
    ]
