# Generated by Django 5.1.4 on 2024-12-14 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_carlist_showroomlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reivew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('comments', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reiviews', to='car_app.carlist')),
            ],
        ),
    ]
